--Lab 2 ? Week 3 (Multi-Line Functions)

--GROUP BY <COMMA SEPERATED FIELDLIST>, HAVING <CONDITIONAL STATEMENTS, BOLLEAN EXPRESSION>
-- 7 AGGREGATE FUNCTIONS = SUM,COUNT,AVG,MIN,MAX,VAR,STDDEV

--Q1
SELECT TO_CHAR(AVG(SALARY) - MIN(SALARY), '$99,999.99') AS Real_Amount
FROM Employees;

--Q2
SELECT
    d.DEPARTMENT_ID,
    TO_CHAR(MAX(e.SALARY), '$999,999,999.99') AS High,
    TO_CHAR(MIN(e.SALARY), '$999,999,999.99') AS Low,
    TO_CHAR(AVG(e.SALARY), '$999,999,999.99') AS Avg
FROM Departments d
JOIN Employees e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID
ORDER BY AVG(e.SALARY) DESC;

--Q3
SELECT
    DEPARTMENT_ID AS "Dept#",
    JOB_ID AS "Job",
    COUNT(*) AS "How Many"
FROM Employees
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING COUNT(*) > 1
ORDER BY "How Many" DESC;


--Q4
SELECT
    JOB_ID AS Job_Title,
    SUM(SALARY) AS Total_Amount_Paid
FROM Employees
WHERE JOB_ID NOT IN ('AD_PRES', 'AD_VP')
GROUP BY JOB_ID
HAVING SUM(SALARY) > 11000
ORDER BY Total_Amount_Paid DESC;

--Q5
SELECT
    MANAGER_ID,
    COUNT(*) AS Supervised_Persons
FROM Employees
WHERE MANAGER_ID IN (100, 101, 102)
GROUP BY MANAGER_ID
HAVING COUNT(*) > 2
ORDER BY Supervised_Persons DESC;

--Q6
SELECT
    DEPARTMENT_ID AS "Dept#",
    MAX(HIRE_DATE) AS "Latest Hire Date",
    MIN(HIRE_DATE) AS "Earliest Hire Date"
FROM Employees
WHERE
    DEPARTMENT_ID IN (10, 20)
GROUP BY DEPARTMENT_ID
HAVING
    MAX(HIRE_DATE) < TO_DATE('2023-01-01', 'YYYY-MM-DD')
ORDER BY "Latest Hire Date" DESC;
