-- ***********************
-- Name: Gyeongrok OH
-- ID: 119140226
-- Date: 10/2/2023
-- Purpose: Lab 3 DBS311
-- ***********************

--Q1  
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (123456, 'Gyeongrok', 'Oh', 'goh3@myseneca.ca', NULL, TRUNC(SYSDATE), 'IT_PROG', NULL, 0.21, 100, 90);

--Q2
UPDATE EMPLOYEES
SET SALARY = 2500
WHERE UPPER(LAST_NAME) IN ('MATOS', 'WHALEN');

--Q3
COMMIT;

--Q4
SELECT LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE UPPER(LAST_NAME) = 'ABEL' 
);

--Q5
SELECT LAST_NAME
FROM EMPLOYEES
WHERE SALARY = (
    SELECT MIN(SALARY)
    FROM EMPLOYEES
);

--Q6
SELECT LOCATIONS.CITY
FROM LOCATIONS
WHERE LOCATION_ID IN (
    SELECT DEPARTMENTS.LOCATION_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENTS.DEPARTMENT_ID IN (
        SELECT EMPLOYEES.DEPARTMENT_ID
        FROM EMPLOYEES
        WHERE EMPLOYEES.SALARY = (
            SELECT MIN(SALARY)
            FROM EMPLOYEES
        )
    )
);

--Q7
SELECT
    (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D2 WHERE D2.DEPARTMENT_ID = E.DEPARTMENT_ID) AS DEPARTMENT_NAME,
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    E.SALARY
FROM
    EMPLOYEES E
WHERE
    (E.DEPARTMENT_ID, E.SALARY) IN (
        SELECT
            DEPARTMENT_ID,
            MIN(SALARY)
        FROM
            EMPLOYEES
        GROUP BY
            DEPARTMENT_ID
    )
ORDER BY
    E.DEPARTMENT_ID;

--Q8
WITH EmployeeLocation AS (
    SELECT
        E.LAST_NAME,
        L.CITY,
        E.SALARY
    FROM
        EMPLOYEES E
    JOIN
        DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN
        LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
),
MinSalaryByCity AS (
    SELECT
        L.CITY,
        MIN(E.SALARY) AS MINSAL
    FROM
        EMPLOYEES E
    JOIN
        DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN
        LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
    GROUP BY
        L.CITY
)
SELECT
    EL.LAST_NAME,
    EL.CITY,
    EL.SALARY
FROM
    EmployeeLocation EL
JOIN
    MinSalaryByCity MSBC ON EL.CITY = MSBC.CITY AND EL.SALARY = MSBC.MINSAL;

--Q9
SELECT
    E1.LAST_NAME,
    E1.SALARY,
    E1.DEPARTMENT_ID
FROM
    EMPLOYEES E1
WHERE 
    E1.SALARY = (
        SELECT
            MIN(E2.SALARY)
        FROM
            EMPLOYEES E2
        WHERE
            E2.SALARY = (
        SELECT
            MAX(SALARY)
        FROM
                    EMPLOYEES
        WHERE
                    DEPARTMENT_ID = E1.DEPARTMENT_ID
            ))
ORDER BY
    E1.DEPARTMENT_ID;

--Q10
SELECT
    E.LAST_NAME,
    E.JOB_ID,
    E.SALARY
FROM
    EMPLOYEES E
WHERE
    E.SALARY IN (
        SELECT
            DISTINCT E2.SALARY
        FROM
            EMPLOYEES E2
        WHERE
            E2.DEPARTMENT_ID = (
                SELECT
                    DEPARTMENT_ID
                FROM
                    DEPARTMENTS
                WHERE
                    UPPER(DEPARTMENT_NAME) = 'IT'
            )
    )
ORDER BY
    E.SALARY ASC,
    E.LAST_NAME;


