-- ***********************
-- Name: Gyeongrok oh
-- ID: 119140226
-- Date: Nov 2, 2023 
-- Purpose: Lab 4 DBS311
-- ***********************
--Q1
SELECT DISTINCT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
WHERE UPPER(JOB_ID) = 'ST_CLERK';

--Q2
SELECT C.COUNTRY_ID, C.COUNTRY_NAME
FROM COUNTRIES C
MINUS
SELECT C.COUNTRY_ID, C.COUNTRY_NAME
FROM COUNTRIES C
JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID






--Q3
-- List departments 10, 50, and 20 in that order with job and department IDs using SET operators
-- List departments 10, 50, and 20 in that order with job and department IDs using SET operators
SELECT D.DEPARTMENT_ID, E.JOB_ID
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 10

UNION all

SELECT D.DEPARTMENT_ID, E.JOB_ID
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 50

minus

(SELECT D.DEPARTMENT_ID, E.JOB_ID
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 10

INTERSECT

SELECT D.DEPARTMENT_ID, E.JOB_ID
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 50)

union all

SELECT D.DEPARTMENT_ID, E.JOB_ID
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 20;

--Q4
SELECT E.EMPLOYEE_ID, E.JOB_ID
 FROM EMPLOYEES E
 JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 WHERE E.JOB_ID IN (
     SELECT JH.JOB_ID
     FROM JOB_HISTORY JH
     WHERE (JH.EMPLOYEE_ID, JH.START_DATE) IN (
         SELECT EMPLOYEE_ID, MIN(START_DATE)
         FROM JOB_HISTORY
         GROUP BY EMPLOYEE_ID
     )
 )

UNION

(SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES

MINUS

SELECT E.EMPLOYEE_ID, E.JOB_ID
FROM EMPLOYEES E
JOIN JOB_HISTORY JH  ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID)


--Q5

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID

UNION 

SELECT
    E.LAST_NAME,
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

